/**
 * Pack export — Markdown / plain text serialisation + browser download.
 *
 * Exports the active language view of a pack so the file reflects
 * whatever the user is currently reading. Everything stays client-side:
 * we read from IndexedDB, render in-memory, and either trigger a Blob
 * download or write to the system clipboard.
 *
 * Format choice rationale
 *  • Markdown is the universal "knowledge worker" interchange (Obsidian,
 *    Notion, Bear, Logseq, GitHub issues, Slack with rendering, …).
 *    A pack exports as a single self-contained .md file.
 *  • Plain text is the lowest-common-denominator option — Notes apps,
 *    email bodies, terminals. Same structure, no `#`/`>`/`-` syntax.
 */

import { activeView, type KnowledgePack } from './pack';

export type ExportFormat = 'markdown' | 'text';

export function packToMarkdown(pack: KnowledgePack): string {
  const view = activeView(pack);
  const date = new Date(pack.createdAt).toISOString().split('T')[0];
  const langChips = pack.outputLanguages.map((l) => l.toUpperCase()).join(' · ');

  const out: string[] = [];

  out.push(`# ${pack.title}`);
  out.push('');
  out.push(`> ${view.summary.short}`);
  out.push('');
  out.push(`**Mode:** ${pack.mode}  · **Source language:** ${pack.sourceLang.toUpperCase()}  · **Translations:** ${langChips}  · **Genre:** ${pack.genre}`);
  out.push('');
  out.push(`**Source:** [${pack.source.url}](${pack.source.url})`);
  out.push('');
  out.push('---');
  out.push('');

  if (view.summary.long) {
    out.push('## Summary');
    out.push('');
    out.push(view.summary.long);
    out.push('');
  }

  if (view.keyIdeas.length > 0) {
    out.push('## Key Ideas');
    out.push('');
    view.keyIdeas.forEach((idea, i) => {
      out.push(`### ${String(i + 1).padStart(2, '0')}. ${idea.title}`);
      out.push('');
      out.push(idea.body);
      out.push('');
    });
  }

  if (view.chapters.length > 0) {
    out.push('## Chapters');
    out.push('');
    view.chapters.forEach((ch) => {
      out.push(`- **${formatTime(ch.startSec)}** — ${ch.title}: ${ch.summary}`);
    });
    out.push('');
  }

  if (view.actionPlan.length > 0) {
    out.push('## Action Plan');
    out.push('');
    view.actionPlan.forEach((step, i) => {
      out.push(`${i + 1}. ${step}`);
    });
    out.push('');
  }

  if (view.vocabulary.length > 0) {
    out.push('## Vocabulary');
    out.push('');
    view.vocabulary.forEach((v) => {
      const pos = v.partOfSpeech ? ` *(${v.partOfSpeech})*` : '';
      out.push(`- **${v.word}**${pos} → ${v.translation}`);
      if (v.context) out.push(`  > ${v.context}`);
    });
    out.push('');
  }

  if (view.quiz.length > 0) {
    out.push('## Quiz');
    out.push('');
    view.quiz.forEach((q, i) => {
      out.push(`### Question ${i + 1}`);
      out.push('');
      out.push(`**Q:** ${q.question}`);
      out.push('');
      out.push(`**A:** ${q.answer}`);
      if (q.explanation) {
        out.push('');
        out.push(`*${q.explanation}*`);
      }
      out.push('');
    });
  }

  if (view.keyQuotes.length > 0) {
    out.push('## Quotes');
    out.push('');
    view.keyQuotes.forEach((q) => {
      out.push(`> "${q.text}"`);
      const meta: string[] = [];
      if (q.speaker) meta.push(q.speaker);
      if (q.timestampSec) meta.push(formatTime(q.timestampSec));
      if (meta.length > 0) out.push(`> — ${meta.join(' · ')}`);
      if (q.original && q.original !== q.text) {
        out.push(`> _${q.original}_`);
      }
      out.push('');
    });
  }

  if (view.socialAngles.length > 0) {
    out.push('## Social Angles');
    out.push('');
    view.socialAngles.forEach((s, i) => {
      out.push(`### Angle ${i + 1}`);
      out.push('');
      out.push(`**Hook:** "${s.hook}"`);
      out.push('');
      out.push(s.caption);
      out.push('');
    });
  }

  out.push('---');
  out.push('');
  out.push(`*Knowledge Pack generated by Voz Clara · ${date}*`);
  out.push(`*A LEON MARÉ product · https://vozclara.pages.dev*`);

  return out.join('\n');
}

export function packToText(pack: KnowledgePack): string {
  // Strip markdown decoration: ``` ` _ * # > [ ] etc.
  // The structure (headings, indentation, separators) stays.
  const view = activeView(pack);
  const date = new Date(pack.createdAt).toISOString().split('T')[0];
  const langChips = pack.outputLanguages.map((l) => l.toUpperCase()).join(' · ');
  const RULE = '─'.repeat(64);

  const out: string[] = [];

  out.push(pack.title.toUpperCase());
  out.push(RULE);
  out.push('');
  out.push(view.summary.short);
  out.push('');
  out.push(`Mode: ${pack.mode}   Source: ${pack.sourceLang.toUpperCase()}   Translations: ${langChips}`);
  out.push(`Genre: ${pack.genre}`);
  out.push(`Source URL: ${pack.source.url}`);
  out.push('');
  out.push(RULE);

  if (view.summary.long) {
    out.push('');
    out.push('SUMMARY');
    out.push('');
    out.push(view.summary.long);
  }

  if (view.keyIdeas.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('KEY IDEAS');
    view.keyIdeas.forEach((idea, i) => {
      out.push('');
      out.push(`  ${String(i + 1).padStart(2, '0')}. ${idea.title}`);
      out.push('');
      out.push(wrapText(idea.body, '      '));
    });
  }

  if (view.chapters.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('CHAPTERS');
    out.push('');
    view.chapters.forEach((ch) => {
      out.push(`  [${formatTime(ch.startSec)}]  ${ch.title} — ${ch.summary}`);
    });
  }

  if (view.actionPlan.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('ACTION PLAN');
    out.push('');
    view.actionPlan.forEach((step, i) => {
      out.push(`  ${i + 1}. ${step}`);
    });
  }

  if (view.vocabulary.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('VOCABULARY');
    out.push('');
    view.vocabulary.forEach((v) => {
      const pos = v.partOfSpeech ? ` (${v.partOfSpeech})` : '';
      out.push(`  ${v.word}${pos}  →  ${v.translation}`);
      if (v.context) out.push(`     "${v.context}"`);
    });
  }

  if (view.quiz.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('QUIZ');
    view.quiz.forEach((q, i) => {
      out.push('');
      out.push(`  Q${i + 1}: ${q.question}`);
      out.push(`  A:  ${q.answer}`);
      if (q.explanation) out.push(`      ${q.explanation}`);
    });
  }

  if (view.keyQuotes.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('QUOTES');
    out.push('');
    view.keyQuotes.forEach((q) => {
      out.push(`  "${q.text}"`);
      const meta: string[] = [];
      if (q.speaker) meta.push(q.speaker);
      if (q.timestampSec) meta.push(formatTime(q.timestampSec));
      if (meta.length > 0) out.push(`     — ${meta.join(' · ')}`);
      if (q.original && q.original !== q.text) out.push(`     (${q.original})`);
      out.push('');
    });
  }

  if (view.socialAngles.length > 0) {
    out.push('');
    out.push(RULE);
    out.push('');
    out.push('SOCIAL ANGLES');
    view.socialAngles.forEach((s, i) => {
      out.push('');
      out.push(`  ${i + 1}. Hook: "${s.hook}"`);
      out.push('');
      out.push(wrapText(s.caption, '     '));
    });
  }

  out.push('');
  out.push(RULE);
  out.push('');
  out.push(`Knowledge Pack generated by Voz Clara · ${date}`);
  out.push('A LEON MARÉ product · https://vozclara.pages.dev');

  return out.join('\n');
}

/**
 * Trigger a browser download of the given content as a file. Uses an
 * in-memory Blob URL that's revoked right after the click — no leftover
 * URLs in memory, no DOM detritus.
 */
export function downloadFile(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Defer revoke so Safari has time to flush the navigation.
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

/**
 * Copy a string to the system clipboard. Returns true on success. Uses
 * the modern Async Clipboard API where available, falls back to the
 * legacy execCommand path on older browsers + iOS Safari edge cases.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // fall through to legacy
    }
  }
  if (typeof document === 'undefined') return false;
  try {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

/**
 * Build a sensible filename for an exported pack, e.g.
 *   "tagesschau-20-00-uhr-03-05-2026-es.md"
 * Strips diacritics, lowercases, joins words with hyphens, appends the
 * active language and the requested extension.
 */
export function exportFilename(pack: KnowledgePack, ext: 'md' | 'txt'): string {
  const slug = slugify(pack.title || 'voz-clara-pack');
  return `${slug}-${pack.outputLang}.${ext}`;
}

/* ─── internals ────────────────────────────────────────────────────────── */

function slugify(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

function wrapText(s: string, indent: string, width = 70): string {
  // Simple word-wrapper for plain-text export so paragraphs read well
  // in fixed-width contexts (terminal, Mail.app plain text mode).
  const words = s.split(/\s+/);
  const lines: string[] = [];
  let current = indent;
  for (const w of words) {
    if (current.length + w.length + 1 > width + indent.length) {
      lines.push(current.trimEnd());
      current = indent + w + ' ';
    } else {
      current += w + ' ';
    }
  }
  if (current.trim()) lines.push(current.trimEnd());
  return lines.join('\n');
}
